In [1]:
import json
import pprint
import pandas as pd
import time
import lol_data_crawling_2
# challenger, grandmaster, diamond

rank_name = 'diamond1'
# bot leblanc
api_key = 'RGAPI-e7499f83-12b5-4685-a191-0c48b46311e2'
# key ~ 2020.08.11. 오후 2시
# lol_data_crawling_2.call_rank_data_for_dia(rank_name, api_key, 34)
print("1단계 완료")
# lol_data_crawling_2.get_accountid(rank_name, api_key)
print("2단계 완료")
lol_data_crawling_2.get_match_data(rank_name, api_key)
print("3단계 완료")

1단계 완료
2단계 완료
매치데이터 수집 진행중
0
63
78
93
100
143
178
188
197
200
252
254
300
318
361
375
400
461
500
535
600
644
700
741
800
856
900
902
1000
1017
1032
1100
1177
1200
1241
1279
1300
1305
1320
1342
1352
1400
1441
1463
1500
1579
1585
1600
1700
1722
1736
1750
1800
1806
1822
1851
1900
1953
1965
2000
2027
2040
2100
2108
2169
2200
2223
2300
2318
2400
2500
2597
2600
2622
2639
2679
2682
2691
2700
2758
2789
2795
2800
2839
2861
2895
2900
2928
2986
3000
3023
3024
3100
3200
3210
3254
3300
3312
3400
3426
3452
3500
3600
3640
3643
3700
3729
3775
3779
3800
3810
3900
4000
4014
4062
4100
4121
4128
4143
4148
4200
4296
4300
4304
4309
4335
4343
4400
4446
4500
4516
4575
4600
4601
4660
4675
4700
4799
4800
4830
4832
4870
4871
4900
4982
4987
5000
5006
5022
5100
5150
5199
5200
5202
5268
5272
5273
5300
5303
5317
5318
5346
5348
5356
5372
5378
5400
5496
5500
5546
5557
5600
5643
5655
5681
5700
5720
5758
5800
5835
5846
5874
5884
5900
5971
6000
6005
6022
6023
6037
6049
6059
6060
6079
6100
6112
6143
6168
6175
6187
6200
6200
6238
6275
6276
6300
6311
6335
6390
6400
6400
6412
6500
6576
6600
6643
6700
6719
6720
6728
6734
6798
6800
6827
<class 'pandas.core.frame.DataFrame'>
Int64Index: 670139 entries, 0 to 99
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   platformId  670139 non-null  object
 1   gameId      670139 non-null  int64
 2   champion    670139 non-null  int64
 3   queue       670139 non-null  int64
 4   season      670139 non-null  int64
 5   timestamp   670139 non-null  int64
 6   role        670139 non-null  object
 7   lane        670139 non-null  object
dtypes: int64(5), object(3)
memory usage: 46.0+ MB
3단계 완료